import { Footer } from './components/Footer/Footer'
import { Merienda, Raleway } from 'next/font/google'
import './styles/globals.scss'

const merienda = Merienda({ subsets: ['latin'], variable: '--font-merienda' })
const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway' })

export const metadata = {
  title: 'AvoriazLoc',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${merienda.variable} ${raleway.variable}`}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
